### ISSUE TITLE
Tabletop compiling issue

### ISSUE THREAD

**Issue by nosepas1** [wg-perception/tabletop#25]
I have tried to download and build from source the tabletop method and I get this compiling error: 

In file included from /home/marti/catkin_ws/src/tabletop/src/object/ObjectRecognizer.cpp:50:0:
/home/marti/catkin_ws/src/tabletop/include/tabletop/object/tabletop_object_detector.h: In member function ‘void tabletop_object_detector::TabletopObjectRecognizer::objectDetection(std::vector<std::vector<cv::Vec<float, 3> > >&, float, bool, std::vector<tabletop_object_detector::TabletopObjectRecognizer::TabletopResult>&)’:
/home/marti/catkin_ws/src/tabletop/include/tabletop/object/tabletop_object_detector.h:115:65: error: no matching function for call to ‘cv::flann::Index::build(cv::Mat&, cv::flann::KDTreeIndexParams)’
         search[i].build(features, cv::flann::KDTreeIndexParams());
                                                                 ^
/home/marti/catkin_ws/src/tabletop/include/tabletop/object/tabletop_object_detector.h:115:65: note: candidate is:
In file included from /usr/local/include/opencv2/flann/flann.hpp:51:0,
                 from /home/marti/catkin_ws/src/tabletop/include/tabletop_object_detector/exhaustive_fit_detector.h:43,
                 from /home/marti/catkin_ws/src/tabletop/include/tabletop/object/tabletop_object_detector.h:41,
                 from /home/marti/catkin_ws/src/tabletop/src/object/ObjectRecognizer.cpp:50:
/usr/local/include/opencv2/flann/miniflann.hpp:137:26: note: virtual void cv::flann::Index::build(cv::InputArray, cv::InputArray, const cv::flann::IndexParams&, cvflann::flann_distance_t)
     CV_WRAP virtual void build(InputArray wholefeatures, InputArray additionalfeatures, const IndexParams& params, cvflann::flann_distance_t distType=cvflann::FLANN_DIST_L2);
                          ^
/usr/local/include/opencv2/flann/miniflann.hpp:137:26: note:   candidate expects 4 arguments, 2 provided
make[2]: *** [tabletop/src/object/CMakeFiles/tabletop_object_ectomodule.dir/ObjectRecognizer.cpp.o] Error 1
make[1]: *** [tabletop/src/object/CMakeFiles/tabletop_object_ectomodule.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j2 -l2" failed

Anyone knows what's happening here? 
Thank you in advance!

**Comment by hris2003** [comment]
Please cite Opencv version that you're using so that we can reproduce the error? Thank you.

**Comment by nlyubova** [comment]
And the flann version?

**Comment by nosepas1** [comment]
I'm using OpenCV 2.4.12

**Comment by vrabaud** [comment]
OpenCV 2.4.12 is the only one with that API, please confirm that master is working for you, just pushed a potential fix.

**Comment by nosepas1** [comment]
Hi,

today I just git pull the origin master and it has worked without any problem, I could compile the tabletop!

**Comment by nlyubova** [comment]
Great! Enjoy ! And try linemod
