### ISSUE TITLE
tabletop object detection error

### ISSUE THREAD

**Issue by fan5ga** [wg-perception/tabletop#26]
I tried Object Recognition Using Tabletop, and successfully found planes by command:
rosrun object_recognition_core detection -c `rospack find object_recognition_tabletop`/conf/detection.table.ros.ork
however failed with detecting objects. outputs as below: 
n-PC:~$ rosrun object_recognition_core detection -c  `rospack find object_recognition_tabletop`/conf/detection.object.ros.ork
[ INFO] [1462467175.269440647]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1462467175.870506603]: System already initialized. node_name: /object_recognition_server
[ INFO] [1462467176.817163521]: System already initialized. node_name: /object_recognition_server
[ INFO] [1462467176.844326959]: Subscribed to topic:/camera/depth_registered/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1462467176.851451746]: Subscribed to topic:/camera/rgb/image_color [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1462467176.867486046]: Subscribed to topic:/camera/depth_registered/image_raw [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1462467176.878455711]: Subscribed to topic:/camera/rgb/camera_info [queue_size: 1][tcp_nodelay: 0]
126 :: 0.5 , 1 , 0.995004 , /base_link , /head_mount_kinect_rgb_optical_frame
[ INFO] [1462467177.544438519]: publishing to topic:/tabletop/clusters
[ INFO] [1462467177.547706797]: publishing to topic:/table_array
Loading model: 8084c0c1974909d0519e05e401006ee2 for object id: 8084c0c1974909d0519e05e401006d09Info,  T0: Load /tmp/fileeMr8CE.obj
Info,  T0: Found a matching importer for this file format
Info,  T0: Import root directory is '/tmp/'
Error, T0: OBJ: No object detected to attach a new mesh instance.
Skipping one or more lines with the same contents
Info,  T0: Entering post processing pipeline
Warn,  T0: RemoveVCProcess: AI_CONFIG_PP_RVC_FLAGS is zero.
Info,  T0: OptimizeGraphProcess finished; Input nodes: 4, Output nodes: 1
Warn,  T0: Found 32 degenerated primitives
Info,  T0: TriangulateProcess finished. All polygons have been triangulated.
Info,  T0: Points: 0, Lines: 1, Triangles: 3, Polygons: 0 (Meshes, X = removed)
Info,  T0: JoinVerticesProcess finished | Verts in: 1472 out: 427 | ~71.0%
Error, T0: This algorithm works on triangle meshes only
Info,  T0: Cache relevant are 3 meshes (512 faces). Average output ACMR is 0.812500
Info,  T0: Leaving post processing pipeline
Traceback (most recent call last):
  File "/home/longtan/ork/src/object_recognition_core/apps/detection", line 24, in <module>
    run_plasm(args, plasm)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = pipeline2

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = <class 'object_recognition_tabletop.ecto_cells.tabletop_object.ObjectRecognizer'>

[function_name] = process_with_only_these_inputs

[type] = std::bad_alloc

[what] = std::bad_alloc

[when] = While triggering param change callbacks

Thanks in advance.

**Comment by hris2003** [comment]
Have you ever had tabletop successfully detecting objects before? Or this is the first time you work with tabletop? What mesh do you use for the detection? Is it the coke mesh from tabletop repository?

**Comment by fan5ga** [comment]
Yeah, I am new to ork. It is my first time to deal with it and never succeed.  I got the coke related files  from the linemod/data folder.

**Comment by hris2003** [comment]
It seems like you followed the 'Compile from source code' tutorial to install tabletop. Have you ever tried using sudo apt-get install ros-<your ROS distro>-object-recognition-tabletop to see if the debian package works?

**Comment by fan5ga** [comment]
yeah. i did. I will try install ros--object-recognition-tabletop instead now. Thank you

**Comment by fan5ga** [comment]
I tried apt-get install.. however it did't help. the same output as previous trail. By the way, i am using ork_renderer with option(USE_GLUT "Use GLUT instead of OSMesa" ON).

**Comment by hris2003** [comment]
Can you provide the error message?

**Comment by fan5ga** [comment]
same as before.

longtan@longtan-PC:~$ rosrun object_recognition_core detection -c  `rospack find object_recognition_tabletop`/conf/detection.object.ros.ork
[ INFO] [1462486433.839405730]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1462486434.328510799]: System already initialized. node_name: /object_recognition_server
[ INFO] [1462486434.894243824]: System already initialized. node_name: /object_recognition_server
[ INFO] [1462486434.909886801]: Subscribed to topic:/camera/depth_registered/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1462486434.930831894]: Subscribed to topic:/camera/rgb/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1462486434.938212497]: Subscribed to topic:/camera/rgb/image_color [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1462486434.952112409]: Subscribed to topic:/camera/depth_registered/image_raw [queue_size: 1][tcp_nodelay: 0]
126 :: 0.5 , 1 , 0.995004 , /base_link , /head_mount_kinect_rgb_optical_frame
[ INFO] [1462486435.490460645]: publishing to topic:/tabletop/clusters
[ INFO] [1462486435.492268410]: publishing to topic:/table_array
Loading model: b13dd957edb402466347244d960021b7 for object id: b13dd957edb402466347244d96001c25Info,  T0: Load /tmp/filekliDX5.obj
Info,  T0: Found a matching importer for this file format
Info,  T0: Import root directory is '/tmp/'
Error, T0: OBJ: No object detected to attach a new mesh instance.
Skipping one or more lines with the same contents
Info,  T0: Entering post processing pipeline
Warn,  T0: RemoveVCProcess: AI_CONFIG_PP_RVC_FLAGS is zero.
Info,  T0: OptimizeGraphProcess finished; Input nodes: 4, Output nodes: 1
Warn,  T0: Found 32 degenerated primitives
Info,  T0: TriangulateProcess finished. All polygons have been triangulated.
Info,  T0: Points: 0, Lines: 1, Triangles: 3, Polygons: 0 (Meshes, X = removed)
Info,  T0: JoinVerticesProcess finished | Verts in: 1472 out: 427 | ~71.0%
Error, T0: This algorithm works on triangle meshes only
Info,  T0: Cache relevant are 3 meshes (512 faces). Average output ACMR is 0.812500
Info,  T0: Leaving post processing pipeline
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/object_recognition_core/detection", line 24, in <module>
    run_plasm(args, plasm)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = pipeline2

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = <class 'object_recognition_tabletop.ecto_cells.tabletop_object.ObjectRecognizer'>

[function_name] = process_with_only_these_inputs

[type] = std::bad_alloc

[what] = std::bad_alloc

[when] = While triggering param change callbacks




longtan@longtan-PC:~$

**Comment by hris2003** [comment]
For such an error, I would go for checking if either something's wrong with the mesh or something's wrong with the libraries that tabletop uses to load the mesh. In your case, you're using the coke mesh from ORK repository, so this eliminates my first option. 

For the second option, can you tell us what version of your linux distro, OpenCV, GLUT, and osmesa installed on your computer, please?

**Comment by fan5ga** [comment]
linux:     Ubuntu 14.04.4 LTS
opencv: libopencv 2.4.8
glut: libglut 3.9.0
GLUT:   libosmesa 6.5.3

**Comment by fan5ga** [comment]
During the training of linemod, the same error (Error, T0: OBJ: No object detected to attach a new mesh instance) occurred. You mean the problem may be the mesh or loading mesh part?  I will look into it.

**Comment by fan5ga** [comment]
Thank you for your suggestion. Problem solved.
It is exactly the mesh caused the problem. I tried the ork_tutorials/data/coke.stl, it turns out to be fine！
