### ISSUE TITLE
Change the sensor source

### ISSUE THREAD

**Issue by Wesley-Lin** [wg-perception/tabletop#32]
Hi All,

I would like to use another depth sensor instead of kinect, Which parts did I need to change to match my sensor's topics ? like as 
rgb_frame_id: camera_rgb_optical_frame
rgb_image_topic: /camera/rgb/image_rect_color
rgb_camera_info: /camera/rgb/camera_info
depth_image_topic: /camera/depth_registered/image_raw
depth_camera_info: /camera/depth_registered/camera_info

**Comment by hris2003** [comment]
Normally you can change the topic names in the [configuration file](https://github.com/wg-perception/tabletop/blob/master/conf/detection.object.ros.ork), the source1 part.
